### ISSUE TITLE
AsyncBot的事件回调是否应并发运行

### ISSUE THREAD

**Issue by xjzh123** [Hiyoteam/hvicorn#4]
这样一来，如果一个回调里面调用了耗时的异步操作，将不会阻塞其余回调。

（实际上，现在的这种模式，几乎没有使用任何“异乎寻常”的控制流，这很可能导致，一个回调里耗时的异步操作，甚至会阻塞后续消息的接收，这样一来，使用协程的优势几乎没有。不过我一时之间说不出来要如何解决这个问题。）

**Comment by 0x24a** [comment]
Hvicorn 有一个工具装饰器，`@threaded`，用于让函数在新线程中运行。
如果任何回调函数都开一个新线程，那可能就没必要了。
而且这样确实可能会造成一些难以解决的问题。
